[package]
name = "spacegate-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = "4.5.37"
iroh = "0.34.0"
iroh-base = "0.34.0"
tokio = "1.44.1"
tokio-rustls = "0.26.2"
webpki-roots = "1.0.0"
